project_version: 1-SNAPSHOT

# base
zulu8_version: 8.74.0.17
jdk8_version: 8.0.392

zulu17_version: 17.46.19
jdk17_version: 17.0.9

jdk21_enabled: false
zulu21_version: 21.30.15
jdk21_version: 21.0.1

s3_enabled: false
aws_java_sdk_version: 1.12.620

# components
kerberos_enabled: false

hadoop_version: 3.3.6

hive_version: 2.3.9

zeppelin_enabled: true
zeppelin_version: 0.11.0
zeppelin_custom_name: all

zookeeper_version: 3.8.4

scala_binary_version: 2.12

spark_enabled: true
spark_binary_version: 3.5
spark_hadoop_version: 3.3.4
spark_version: 3.5.1

flink_enabled: false
flink_binary_version: 1.18
flink_version: 1.18.1
flink_hive_version: 2.3.9

kyuubi_enabled: true
kyuubi_version: 1.9.2
kyuubi_hadoop_version: 3.3.6

ranger_enabled: false
ranger_version: 2.4.0

trino_enabled: false
trino_version: 436

iceberg_enabled: true
iceberg_version: 1.5.2

hudi_enabled: false
hudi_version: 0.14.1

kafka_enabled: false
kafka_version: 2.8.1

grafana_enabled: false
grafana_version: 11.0.0

prometheus_enabled: false

loki_enabled: false
loki_version: 3.0.0
loki_log4j2_appender_version: 0.9.32

# repository
repository_apache: https://mirrors.cloud.tencent.com/apache
repository_maven: https://mirrors.cloud.tencent.com/maven

apt_mirror_enabled: true
